version: '3.1'

services:

  mongo:
    image: mongo:4.0.2-xenial
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blog

# docker-compose up
# mongo --username root --password password --authenticationDatabase admin blog